<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use LokiCheckout\MultiSafepay\Component\PaymentComponent\PaymentComponentViewModel;
use Loki\Components\Util\Block\CssClass;

/** @var PaymentComponentViewModel $viewModel */
/** @var Template $block */
/** @var CssClass $css */
$gatewayCode = $viewModel->getGatewayCode();
?>
<div class="<?= /* @noEscape */
$css('') ?>" data-gateway-id="<?= $escaper->escapeHtml($gatewayCode) ?>">
    <div id="<?= $escaper->escapeHtml($viewModel->getElementId()) ?>-container"></div>
</div>
