<?php
declare(strict_types=1);

/** @version 2.0.3 */

use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use LokiCheckout\MultiSafepay\Component\PaymentComponent\PaymentComponentViewModel;
use Loki\CssUtils\Util\CssClass;

/** @var Escaper $escaper */
/** @var PaymentComponentViewModel $viewModel */
/** @var Template $block */
/** @var CssClass $css */
$gatewayCode = $viewModel->getGatewayCode();
?>
<div class="<?= /* @noEscape */ $css('') ?>" data-gateway-id="<?= $escaper->escapeHtml($gatewayCode) ?>">
    <div id="<?= $escaper->escapeHtml($viewModel->getElementId()) ?>-container"></div>
</div>
