<?php
declare(strict_types=1);

/** @version 2.0.8 */

use Magento\Framework\View\Element\Template;
use LokiCheckout\MultiSafepay\ViewModel\AssetConfig;
use Loki\Components\Factory\ViewModelFactory;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var AssetConfig $assetConfig */
$assetConfig = $viewModelFactory->create(AssetConfig::class);
?>
<link rel="stylesheet" href="<?= /* @noEscape */ $assetConfig->getComponentCssUrl() ?>">
